spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://sazfaraz779_db_user:gtnhK3VwROXMBp8z@cluster0.95gwwuh.mongodb.net/?appName=Cluster0

spring.data.mongodb.database=flowbrain

jwt.secret=thisIsMyVeryLongSecretKeyForFlowBrainApplication123456789
jwt.expiration=86400000