spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://sazfaraz779_db_user:gtnhK3VwROXMBp8z@cluster0.95gwwuh.mongodb.net/?appName=Cluster0

spring.data.mongodb.database=flowbrain

jwt.secret=thisIsMyVeryLongSecretKeyForFlowBrainApplication123456789
jwt.expiration=86400000


# =========================
# Mistral AI
# =========================

mistral.api.key=KCJKxKTcKuxp7uwdNjKDFnS73kNTBkkK

mistral.base.url=https://api.mistral.ai/v1/chat/completions

mistral.model=mistral-small-latest

spring.ai.vectorstore.mongodb.collection-name=flowbrain_vectors

spring.ai.vectorstore.mongodb.index-name=vector_index

spring.ai.vectorstore.mongodb.initialize-schema=true