spring.application.name=backend

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=flowbrain

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# =========================
# Mistral AI
# =========================

mistral.api.key=${MISTRAL_API_KEY}
mistral.base.url=https://api.mistral.ai/v1/chat/completions
mistral.model=mistral-small-latest

spring.ai.vectorstore.mongodb.collection-name=flowbrain_vectors
spring.ai.vectorstore.mongodb.index-name=vector_index
spring.ai.vectorstore.mongodb.initialize-schema=true